### ISSUE TITLE
Stryker hanging on the very last test

### ISSUE THREAD

**Issue by andrepm06** [stryker-mutator/stryker#932] opened 2018-07-02 16:53 UTC
Hello,

I'm, currently facing an annoying issue:

During my tests execution my very last test doesn't end. So stryker hangs at 100% and i never gets the report.

I've tested a few combinations to figure this out, but the best so far i only discovered that this happens when i have approximately 400 mutators running. At the moment, the folder which i'm targeting generates 1366 mutators. But i have plans to run in more folders of my project. 

Here are my dependencies:
```
"stryker": "0.21.1",
    "stryker-api": "0.15.0",
    "stryker-html-reporter": "0.14.2",
    "stryker-javascript-mutator": "0.5.0",
    "stryker-jest-runner": "0.5.1"
```

Here is my conf:
```
module.exports = function(config) {
  config.set({
    mutate: [
      "src/components/**/*.js",
      "!src/components/**/*.spec.js",
      "!src/components/**/*.stories.js",
      "!src/components/**/styles.js",
      "!src/components/**/*.snap.js"
    ],
    testRunner: 'jest',
    reporter: ['clear-text', 'progress', 'html'],
    coverageAnalysis: 'off',
    mutator: 'javascript',
    logLevel: 'debug',
    timeoutMs: 300000
  })
  
};
```

**Comment by nicojs** [comment] 2018-07-03 08:28
@andrepm06 thanks for reporting this issue.

How long did you wait for Stryker to hang at 100%? I Stryker might be waiting on one or more mutants that are still being tested. You specify a `timeoutMs` of `300000` (5 minutes).

Could you try without the `timeoutMs` option (the default value should be fine).

More background info:

Stryker can mutate your code in such a way that it creates an infinite loop. For example:

```js
let i = 0;
while(i < 10){
   i++;
}
```

Stryker might mutate this to:

```js
let i = 0;
while(i < 10){
   i--;
}
```

This would be an infinite loop. Stryker will wait a calculated amount of time before killing off this test runner and reporting the mutant as `Timeout`. 

For more info on timeouts, please see https://github.com/stryker-mutator/stryker/tree/master/packages/stryker#global-timeout-in-milliseconds

**Comment by andrepm06** [comment] 2018-07-03 14:31
> How long did you wait for Stryker to hang at 100%?

More than 5 minutes for sure.

Also, removing `timeoutMs` i have 721 tests being running in 20 minutes, but all of them timed out.

**Comment by nicojs** [comment] 2018-07-03 15:27
What OS are you running? If you're running on linux of mac: I might know what the cause is.

For the timeout issue: this should actually be fixed. I've implemented a fix here: https://github.com/stryker-mutator/stryker/commit/ad06c115cac064a02dc90f7a446966c2cc2219b7#diff-d43e1982197040e98ca0edb58dc5ddaa however, it seems that it didn't end up in the changelog for some reason.

@simondel any idea what went wrong there?

@andrepm06 upgrading to these versions will fix that issue, but still leave you with the issue of Stryker not closing I'm afraid.

```
 - stryker-api@0.17.2
 - stryker-html-reporter@0.14.2
 - stryker-javascript-mutator@0.7.2
```

**Comment by andrepm06** [comment] 2018-07-03 16:41
I'm running in MacOS 10.13.3.

I've upgraded the dependencies as you suggested, but timeouts are still there.

**Comment by nicojs** [comment] 2018-07-04 15:13
Sorry, forgot the dependency update for _stryker itself_ :(. Could you try it? stryker@0.24.2 (just did a new release with a fix that might you ==> 0.24.2).

If that doensn't work I need some more information. Could you attach a screenshot of the console output and a screenshot of your processes?

**Comment by andrepm06** [comment] 2018-07-05 15:12
@nicojs I think i cannot share my running processes, but I've attached the npm processes running. What do you need?

![captura de tela 2018-07-05 as 12 09 16](https://user-images.githubusercontent.com/6975975/42331682-6cecdd6c-804c-11e8-8bf7-88e241ad1ec0.png)

<img width="1265" alt="captura de tela 2018-07-05 as 12 09 28" src="https://user-images.githubusercontent.com/6975975/42331681-6cc2e3a4-804c-11e8-9293-afb4ef4fc36a.png">

**Comment by andrepm06** [comment] 2018-07-14 16:45
@nicojs Not worked =(

**Comment by jeffreyscholz** [comment] 2018-08-03 20:39
I don't know if this is helpful, but I had the same issue. It went away after I used explicit whitelists and used no blacklist for the `mutate` field. I'm using this in node, and my suspicion is that some weird framework file or dependency gets mutated and that causes the hang. I don't know what the root cause is.

**Comment by andrepm06** [comment] 2018-08-03 20:41
@jeffreyscholz You mean, expliciting the files which i want to mutate?

**Comment by jeffreyscholz** [comment] 2018-08-03 20:59
@andrepm06 no, folder level. For example, in my node project I did `[middleware/**/*.js, routes/**/*.js, ...]`. I suggest only allowing a small subset into the mutation then slowly expanding it until you see the error pop up again. I realize this is not a real fix, but this is what I ended up doing.

**Comment by nicojs** [comment] 2018-08-07 12:11
@andrepm06 could you try this again after upgrading to 0.26.1? We changed the core of how we spawn and handle test runners in child processes. 

In addition, could you try to use [wtfnode](https://www.npmjs.com/package/wtfnode) to run Stryker? For example: `wtfnode node_modules/.bin/stryker run`. When Stryker hangs again, it will output the reason to the screen after interrupting the application (CTRL+C). Worked like a charm for me when I was debugging reasons for hanging applications earlier this week.

**Comment by andrepm06** [comment] 2018-08-09 16:07
It worked!

`"stryker": "0.26.1",
   "stryker-api": "0.18.0",
   "stryker-html-reporter": "0.14.2",
   "stryker-javascript-mutator": "0.7.2",
   "stryker-jest-runner": "0.5.1",`

**Comment by simondel** [comment] 2018-08-09 16:18
Awesome! nice to hear that it has been fixed. I'll close this issue for now. If the issue comes back, please let it know!

**Closed by simondel** 2018-08-09 16:18 UTC
