### ISSUE TITLE
Error when run stryker with MochaTestRunner - ReferenceError: ready is not defined

### ISSUE THREAD

**Issue by jtlimo** [stryker-mutator/stryker#1892] opened 2019-11-25 22:04 UTC
**Summary**

Error when trying to running stryker. The test try to execute but failed quickly with the error:

```
19:46:40 (90212) DEBUG MochaTestRunner Starting Mocha test run
undefined:4
return (ready);
^

ReferenceError: ready is not defined
    at eval (eval at deserialize (/home/jess/Projects/work/undefined/backend/gupy-api-darthvader/node_modules/surrial/src/index.js:17:18), <anonymous>:4:1)
    at Object.deserialize (/home/jess/Projects/work/undefined/backend/gupy-api-darthvader/node_modules/surrial/src/index.js:18:19)
    at ChildProcess.worker.on (/home/jess/Projects/work/undefined/backend/gupy-api-darthvader/node_modules/@stryker-mutator/core/src/child-proxy/ChildProcessProxy.js:123:43)
    at ChildProcess.emit (events.js:182:13)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Stryker config**

```js
module.exports = function(config){
  config.set({
    mutator: 'javascript',
    mutate: ['./components/**/*.test.js'],
    packageManager: 'npm',
    reporters: ['clear-text', 'progress'],
    testRunner: 'mocha',
    testFramework: 'mocha',
    coverageAnalysis: 'off',
    mochaOptions: {
      spec: ['./components/**/*.test.js'],
      opts: './test/mocha.opts',
    },
  });
}
```

**Test runner config**

Mocha.opts
```
--timeout=50000
--reporter=progress
--require ts-node/register
--require ./test/MochaBootstrap.js
--require ./test/mocha.env.js
--exit
```

**Stryker environment**

```
├─┬ @stryker-mutator/core@2.4.0
│ ├─┬ @stryker-mutator/api@2.4.0
│ ├── @stryker-mutator/util@2.4.0
├─┬ @stryker-mutator/javascript-mutator@2.4.0
│ ├── @stryker-mutator/api@2.4.0 deduped
├─┬ @stryker-mutator/mocha-framework@2.4.0
│ └── @stryker-mutator/api@2.4.0 deduped
├─┬ @stryker-mutator/mocha-runner@2.4.0
│ ├── @stryker-mutator/api@2.4.0 deduped
├─┬ @stryker-mutator/typescript@2.4.0
│ ├── @stryker-mutator/api@2.4.0 deduped
│ ├── @stryker-mutator/util@2.4.0 deduped

```

```json
+-- mocha@6.2.0

```

**Test runner environment**

```shell
# Test command
"NODE_ENV=${NODE_ENV:=test} mocha 'components/**/*.test.js'"
```

**Mocha.opts**
```json

--timeout=50000
--reporter=progress
--require ts-node/register
--require ./test/MochaBootstrap.js
--require ./test/mocha.env.js
--exit
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 10.14.1
| npm              | 6.4.1
| Operating System  | Linux 

**Add stryker.log**

**Comment by brodybits** [comment] 2019-11-26 02:24
Reproduction project would increase your chances of others reproducing and possibly fixing your issue.

I would also recommend you consider trying the command test runner. I have had better luck with the command test runner in quite a few cases.

**Comment by kmdrGroch** [comment] 2019-11-26 11:03
Totally agree with Brody. The issue is probably caused that mocha opts are not read correctly. If you can provide some reproduction of it, we could debug it faster.

**Comment by jtlimo** [comment] 2019-11-26 13:19
@kmdrGroch e @brodybits  How I can provide some reproduction? I really don't know how to do this. :disappointed:

**Comment by kmdrGroch** [comment] 2019-11-26 13:43
If your project isn't private, you could provide link to it. If it's private, try writing similar app (just smaller one, but with the same configuration)

**Comment by jtlimo** [comment] 2019-11-26 13:52
Okay @kmdrGroch . My project it's private.
I need to write a similar application? :open_mouth: 
When you say similar it's the features or structure?

**Comment by kmdrGroch** [comment] 2019-11-26 13:54
Structure. I just need the same configuration. I really don't care about features / your code. It normally doesn't brake anything :)

**Comment by kmdrGroch** [comment] 2019-11-26 13:55
The easiest thing is to remove all files from your SRC and TEST folder, provide some simple one source file and test file.

**Comment by jtlimo** [comment] 2019-11-26 17:13
Okay @kmdrGroch . I'll try this and share the repository as soon as possible.

**Comment by jtlimo** [comment] 2019-12-09 19:54
Hello, I come back. ;)

I create an example repo: https://github.com/jtlimo/stryker-example
but doesn't throw any error :/

In real life project, I receive some warnings that I guess is the problem.

16:56:19 (31931) TRACE ChildProcessProxy WARNING: NODE_ENV value of 'test' did not match any deployment config file names.
16:56:19 (31931) TRACE ChildProcessProxy WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode

at eval (eval at deserialize (/home/jlima/Documentos/Projects/undefined/backend/gupy-api-darthvader/node_modules/surrial/src/index.js:17:18), <anonymous>:4:1)

is a stricted but the warnings says my code doesnt runs stricted code? confused

**Comment by jtlimo** [comment] 2019-12-20 20:19
Hello @kmdrGroch some idea why this error occur? 

If need more information, I will try to find out a way to put here

**Comment by kmdrGroch** [comment] 2019-12-20 20:21
They are just warnings... They shouldn't make anything fail. Please provide more data or failing code

**Comment by jtlimo** [comment] 2019-12-20 20:45
OK @kmdrGroch I'll try to reproduce the error on example repository, but it's difficult to reproduce.

**Comment by kmdrGroch** [comment] 2019-12-20 21:22
Without finding the exact error it's hard to fix it :<

**Comment by kmdrGroch** [comment] 2020-10-02 17:17
Does this error still occur?

**Comment by jtlimo** [comment] 2020-10-02 19:08
@kmdrGroch for now this error is not occur, but I issued this new error: 

https://github.com/stryker-mutator/stryker/issues/2185

**Comment by simondel** [comment] 2020-11-20 09:15
Hi! I'm closing this issue for now. We'll continue in #2185

**Closed by simondel** 2020-11-20 09:15 UTC
Labels: 🐛 Bug
