### ISSUE TITLE
Using tsconfig-paths with Stryker

### ISSUE THREAD

**Issue by mattleff** [stryker-mutator/stryker#1153] opened 2018-09-20 20:42 UTC
### Summary

When using `paths` in `tsconfig.json` the path in the `require` call does not match the file path on disk (see https://github.com/Microsoft/TypeScript/issues/5039#issuecomment-206451221). This can be solved by using https://github.com/dividab/tsconfig-paths which patches Node's module loading to calculate the correct module path using the `tsconfig.json` `paths`. The question is how can I use `tsconfig-paths` with Stryker? I attempted to run Stryker using `tsconfig-paths/register` like so: `node -r tsconfig-paths/register -- node_modules/.bin/stryker run` but it returned the same error (see below). What is the correct injection point to load `tsconfig-paths` for Jasmine?

### Stryker config

```js
module.exports = function(config) {
	config.set({
		mutator: 'typescript',
		packageManager: 'npm',
		reporters: ['html', 'clear-text', 'progress'],
		testRunner: 'jasmine',
		transpilers: ['typescript'],
		testFramework: 'jasmine',
		coverageAnalysis: 'perTest',
		jasmineConfigFile: 'spec/support/jasmine.json',
		tsconfigFile: 'tsconfig.json',
		mutate: ['server/**/*.ts'],
		maxConcurrentTestRunners: 1,
		logLevel: 'trace'
	});
};
```

### Stryker environment

```
├─┬ stryker@0.29.2
├─┬ stryker-api@0.21.1
├─┬ stryker-html-reporter@0.16.2
├── stryker-jasmine@0.10.2
├── stryker-jasmine-runner@0.2.2
├─┬ stryker-typescript@0.14.0
```

```
├─┬ jasmine@3.2.0
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | v8.11.3
| npm              | 5.6.0
| Operating System | macOS 10.13.6

### Add stryker.log

```
....
14:29:21 (6338) ERROR InitialTestExecutor One or more tests resulted in an error:
	An error occurred while loading your jasmine specs
Error: Cannot find module '@common/env'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (....../my-project/.stryker-tmp/sandbox7932692/spec/support/knex.helper.js:5:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
14:29:21 (6338) ERROR StrykerCli an error occurred Error: Something went wrong in the initial test run
    at InitialTestExecutor.validateResult (....../my-project/node_modules/stryker/src/process/InitialTestExecutor.js:139:9)
    at InitialTestExecutor.<anonymous> (....../my-project/node_modules/stryker/src/process/InitialTestExecutor.js:45:12)
    at step (....../my-project/node_modules/stryker/node_modules/tslib/tslib.js:133:27)
    at Object.next (....../my-project/node_modules/stryker/node_modules/tslib/tslib.js:114:57)
    at fulfilled (....../my-project/node_modules/stryker/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by nicojs** [comment] 2018-09-24 16:52
Thanks for reporting. I will take a look once I've got some time. It might take a few weeks though.

**Comment by simondel** [comment] 2019-02-13 15:32
We've somehow forgot to look at this, sorry :(

Since Stryker has changed a lot recently, I'm closing this issue. If the problem still persists with the latest version of Stryker, please let us know!

**Closed by simondel** 2019-02-13 15:32 UTC

**Comment by Tarjei400** [comment] 2020-04-09 12:02
I believe it still persists: 

> 
3 import {PropertySummary} from "@api/model/propertySummary";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

14:02:02 (4310) ERROR StrykerCli an error occurred Error: Something went wrong in the initial test run
    at InitialTestExecutor.validateResult (/home/adrian/Projects/zzzing-admin-panel/node_modules/@stryker-mutator/core/src/process/InitialTestExecutor.js:86:15)
    at InitialTestExecutor.run (/home/adrian/Projects/zzzing-admin-panel/node_modules/@stryker-mutator/core/src/process/InitialTestExecutor.js:41:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Stryker.runMutationTest (/home/adrian/Projects/zzzing-admin-panel/node_modules/@stryker-mutator/core/src/Stryker.js:53:38)
14:02:02 (4310) INFO StrykerCli Trouble figuring out what went wrong? Try `npx stryker run --fileLogLevel trace --logLevel debug` to get some more info.

**Comment by NicholasKuchiniski** [comment] 2020-05-28 21:55
I have this issue to, its looks like stryker run the original version of the file when using tsconfig-paths, if i change to the relative path, the tests fails.

**Comment by NicholasKuchiniski** [comment] 2020-05-28 22:17
#2225

**Comment by InfoSec812** [comment] 2021-03-15 19:07
I too am having this issue. I am in the process of creating a simple reproducer project and will post back here once I have it.
