### ISSUE TITLE
Phantomjs processes are not killed on windows environment

### ISSUE THREAD

**Issue by jordyheutinck** [stryker-mutator/stryker#97] opened 2016-04-28 15:18 UTC
Currently, 8 node.js processes will be spawned. Each one of them will then handle 1 phantom.js process. When a node.js process is finished or if a timeout has occurred on one of the node.js processes it will be killed. However, the corresponding phantomjs processes will not be killed. This can result in massive resource hogging when using the tests.
![bug](https://cloud.githubusercontent.com/assets/9082175/14891029/34635c5c-0d65-11e6-90b3-5f5fec4ad14a.png)
Used dependancies:
```
    "karma": "^0.13.22",
    "karma-chrome-launcher": "^0.1.7",
    "karma-coverage": "^0.5.5",
    "karma-html2js-preprocessor": "^0.1.x",
    "karma-jasmine": "^0.2.x",
    "karma-junit-reporter": "^0.2.2",
    "karma-ng-html2js-preprocessor": "^0.1",
    "karma-phantomjs-launcher": "^1.0.0",
    "stryker": "^0.3.2"
```
Windows 7 enterprise, with npm 3.8.7 and node 4.3.1

**Comment by nicojs** [comment] 2016-04-28 21:10
This is a very interesting problem. Thanks a lot for this report! We haven't encountered it before. I tried to reproduce it by adding some e2e tests. The work can be reviewed on branch [hanging-phantomjs-processes](https://github.com/stryker-mutator/stryker/tree/hanging-phantomjs-processes).

However I cannot reproduce this. The problem seems to be platform depended. I'm using Windows 10 myself. Tomorrow I'll try on a windows 7 machine. What is your npm and node version?

```
$ npm --version
3.8.2
$ node --version
v5.9.0
```

**Comment by simondel** [comment] 2016-04-29 06:47
I unfortunately was also unable to reproduce it locally using Windows 10, npm 2.14.12 and node 4.3.1

**Comment by jordyheutinck** [comment] 2016-04-29 07:20
Strange..
Im using windows 7 enterprise, with npm 3.8.7 and node 4.3.1. I'll try and see if I have any time today to reproduce the issue locally with the branch Nico provided

**Comment by phazebroek** [comment] 2016-04-29 08:47
No issues with phantomjs processes on Windows 7 enterprise with npm 2.14.12 and node 5.0.0

**Comment by jordyheutinck** [comment] 2016-04-29 09:25
Updating to node 5.0 did the trick for me. phantomjs.exe now exits nicely.

**Comment by nicojs** [comment] 2016-04-29 10:33
I reopen this issue because we state to support  V >=0.12.0 in our `package.json`. We fix this issue and try if we can reproduce it on linux-based OS'es as well.

**Comment by phazebroek** [comment] 2016-05-04 10:55
FYI: updated my node/npm and it works great with node 6.0.0 and npm 3.8.6!

**Comment by nicojs** [comment] 2016-10-06 16:05
Didn't hear anything from this bug in a long, long time. We can't reproduce it anywhere. Closing this issue.

**Closed by nicojs** 2016-10-06 16:05 UTC
Labels: bug
