### ISSUE TITLE
Frequent timeouts when running tests with Stryker

### ISSUE THREAD

**Issue by mauricedb** [stryker-mutator/stryker#1867] opened 2019-11-19 09:22 UTC
**Summary**

When Running Stryker I frequently see a score of 100% because of tests timing out. This not consitent and varies greatly between runs. The timeouts occur very frequent on a larger TypeScript React project but can also be repeated frequently on a small project.

Note that there is one **empty** test here and all that is needed to reproduce this is an import of a very simple React component.

The test file:
```TypeScript
import Label from "./Label";

test("dummy", () => {});
```

The `Label.tsx` being imported:
```TypeScript
import React, { ReactElement, ReactChild } from "react";

type LabelProps = {
  caption: ReactChild;
  name?: string;
};

const Label = ({ caption, name }: LabelProps): ReactElement => {
  return <label htmlFor={name}>{caption}</label>;
};

Label.displayName = "Label";

export default Label;
```

The initial test run always passed but then subsequent mutation runs sometimes fail with a timeout. These timeouts appear to occur about 20% of the time in the small sample project but are a lot more frequent on a large project. The timeouts in the small project always seem to be either 0, 2 or 4, there are a total of 4 mutant generated. I have seen a run with either 1 or 3 timeouts.

I have uploaded the sample project to a GitHub repository [here](https://github.com/mauricedb/stryker-test)

**Stryker config**

```js
// This config was generated using a preset.
// Please see the handbook for more information: https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/guides/react.md#react
module.exports = function(config) {
  config.set({
    mutate: [
      "src/**/*.ts?(x)",
      "!src/*.ts?(x)",
      "!src/**/*@(.test|.spec|Spec).ts?(x)"
    ],
    mutator: "typescript",
    testRunner: "jest",
    reporters: ["progress", "clear-text", "html"],
    coverageAnalysis: "off",
    tempDirName: "stryker-tmp",
    jest: {
      projectType: "react"
    }
  });
};
```

**Test runner config**

Jest with the standard Create-React-App configuration.

**Stryker environment**

```
stryker-test@0.1.0 C:\Temp\stryker-test
+-- @stryker-mutator/core@2.3.0
| +-- @stryker-mutator/api@2.3.0
| +-- @stryker-mutator/util@2.3.0
+-- @stryker-mutator/html-reporter@2.3.0
| +-- @stryker-mutator/api@2.3.0 deduped
| +-- @stryker-mutator/util@2.3.0 deduped
+-- @stryker-mutator/jest-runner@2.3.0
| +-- @stryker-mutator/api@2.3.0 deduped
+-- @stryker-mutator/typescript@2.3.0
| +-- @stryker-mutator/api@2.3.0 deduped
| +-- @stryker-mutator/util@2.3.0 deduped
```

```
"react-scripts": "3.2.0"
jest@24.9.0
```

**Test runner environment**

```shell
# Test command
yarn test
"test": "react-scripts test",
```

```json
```

**Your Environment**

| software         | version(s)
| ---------------- | -------  
| node             | v10.15.3
| npm              | 6.11.3
| Operating System | Windows 10 version 1809

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker/files/3862950/stryker.log)

**Comment by brodybits** [comment] 2019-11-19 12:49
I would *highly* recommend posting a full demo project for this kind of an
issue in order to increase the chances of others reproducing your
observations.


-- 
Sent from my mobile

**Comment by mauricedb** [comment] 2019-11-19 13:04
@brodybits That is why I included it in the original post.

Here it is again: https://github.com/mauricedb/stryker-test

**Comment by brodybits** [comment] 2019-11-19 14:18
Thanks, my bad. I did encounter something similar, suggest you try using
command runner rather than jest runner as a workaround. You may also want
to consider playing with the timeoutMS setting.

With a disclaimer that I am not a maintainer.

-- 
Sent from my mobile

**Comment by kmdrGroch** [comment] 2019-11-21 16:25
for now, try increasing timeoutMS and see if problem still exists. I guess it might be a bug in package jest configuration or in jest itself since it is the only runner that has so many issues related to timeout :/

**Comment by kmdrGroch** [comment] 2019-11-21 16:28
I'll investigate this problem today. Maybe I'll find a permanent solution

**Comment by kmdrGroch** [comment] 2019-11-21 16:39
I couldn't reproduce this issue :/ every time I get that all survived, no timeout. If it is possible, could you share the original repository?

**Comment by brodybits** [comment] 2019-11-21 16:40
I think he already posted it here: https://github.com/mauricedb/stryker-test

(see comments above)

**Comment by kmdrGroch** [comment] 2019-11-21 17:18
@brodybits I meant 'original'. Since I couldn't reproduce this issue on that repository ^

**Comment by mauricedb** [comment] 2019-11-21 19:01
@kmdrGroch Sorry the original source code is closed source so I can't share that.

I was just running the tests again and was seeing timeouts though not very many. I added a number of copies of the `label` folder to the test project and that seems to make it fail a bit more often. Though still not on ever run.

**Comment by kmdrGroch** [comment] 2019-11-21 19:17
sorry to hear that... Although you increased the number of labels, I still get no timeout :/

my envinfo
```
 System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz 
    Memory: 9.08 GB / 15.92 GB
  Binaries:
    Node: 10.16.3 - D:\Applications\Node\node.EXE
    npm: 6.12.0 - D:\Applications\Node\npm.CMD
  Managers:
    pip3: 19.3.1 - D:\Applications\Python\Scripts\pip3.EXE
  Utilities:
    Git: 2.23.0.
  Languages:
    Python: 3.8.0
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
```

**Comment by kmdrGroch** [comment] 2019-11-21 19:17
@mauricedb if you are using `yarn` try running it via `npm`. And tell me exact command you are using for stryker

**Comment by mauricedb** [comment] 2019-11-21 19:52
@kmdrGroch Not using either Yarn on NPM to start the run, just a simple `stryker run` from a PowerShell console using ConEmu. I did use Yarn to install all NPM packages. Just did another run and 4 timeouts, 96 survived. Deleting `node_modules` and reinstalling with NPM doesn't change anything, first run 6 timeouts and 94 survived.

My machine is not completely idle as I was playing a YouTube video when running Stryker in the background.

**Comment by kmdrGroch** [comment] 2019-11-21 20:00
Nothing comes to my mind, other than either increasing `timeoutMS` in stryker config or decreasing maxConcurrentTestRunners to let's say 2 (since you are using 4 by default [default for your CPU]),

you could also try adding `enableFindRelatedTests` as `false` in `jest` part of config.

So basically try playing with this setup:
```js
module.exports = function(config) {
  config.set({
    mutate: [
      "src/**/*.ts?(x)",
      "!src/*.ts?(x)",
      "!src/**/*@(.test|.spec|Spec).ts?(x)"
    ],
    mutator: "typescript",
    testRunner: "jest",
    reporters: ["progress", "clear-text", "html"],
    coverageAnalysis: "off",
    tempDirName: "stryker-tmp",
    jest: {
      projectType: "react",
      enableFindRelatedTests: false // try adding this
    },
    timeoutMS: 30000, // increase / decrease
    maxConcurrentTestRunners: 2 // try for 1 - 4
  });
};```

**Comment by kmdrGroch** [comment] 2019-11-21 20:02
if you are running CPU heavy apps it might result in different outputs. But I guess it can be fixed via one of these options

**Comment by mauricedb** [comment] 2019-11-21 20:50
@kmdrGroch So far I seem to have the best result with `timeoutMS: 10000` and/or `maxConcurrentTestRunners: 2`. Both seem to eliminate all timeouts so far and keep the total elapsed time roughly the same. Using `enableFindRelatedTests: false` seems to have no effect.

**Comment by kmdrGroch** [comment] 2019-11-21 21:02
@mauricedb so probably it is caused by not enough resources on your PC :/ try running stryker without heavy CPP apps, don't slow down PC, since some inconsistencies can be caused by lag spikes

**Comment by simondel** [comment] 2019-11-22 07:58
@nicojs Are these the issues that you've discussed with Maurice last Wednesday when you two met? If you, is there any more context you could provide?

**Comment by mauricedb** [comment] 2019-11-22 10:22
@simondel Nope, I mostly asked advice about running Stryker on a larger application. If you want we can do a call later today or next week.

**Comment by mauricedb** [comment] 2019-11-23 18:42
An update on my progress here. Updating the Stryker configuration based on suggestions from @kmdrGroch and @nicojs have helped a lot. Running on the shared part of the project that previously failed with 99% timeouts in 75 hours now run in 12 hours with just a few timeouts and a report that is very usable.

The Stryker config I am using is:
```js
module.exports = function(config) {
  config.set({
    mutate: [
      "!src/**/*.ts?(x)",
      "src/shared/**/*.ts?(x)",
      "!src/**/*@(.test|.spec|Spec).ts?(x)"
    ],
    mutator: "typescript",
    testRunner: "jest",
    reporters: ["progress", "clear-text", "html"],
    tempDirName: "stryker-tmp",
    coverageAnalysis: "off",
    jest: {
      projectType: "react"
    },
    timeoutMS: 10000,
    maxConcurrentTestRunners: 2,
    files: [
      "src/**/*.*",
      "!src/**/*.test.ts?(x)",
      "src/shared/**/*.test.ts?(x)"
    ]
  });
};
```

**Closed** 2019-12-17 12:52 UTC
Labels: 🐛 Bug
