### ISSUE TITLE
Setting up Iteration Plan / Roadmaps

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1834] opened 2019-11-09 00:31 UTC
I think it would be nice to set up some iteration plans and roadmaps like it is done in Typescript.
It could help us focus on some topics more than others / show what was changed etc.

**Comment by nicojs** [comment] 2019-11-11 06:58
Yes I agree. What is your suggestion? Add a `roadmap.md` file? @simondel what are your thoughts on this?

**Comment by simondel** [comment] 2019-11-11 07:18
Sounds like a good plan. Since Waffle is dead 🧇😭

Duplicate of: https://github.com/stryker-mutator/stryker/issues/334

**Comment by simondel** [comment] 2019-11-11 07:35
We have a few big topics that we want to fix:
* Excluding specific mutations (https://github.com/stryker-mutator/stryker/issues/1472) (Syntax should be discussed with Stryker.NET and Stryker4s)
* Mutation switching (https://github.com/stryker-mutator/stryker/issues/1514)
* Incremental analysis (https://github.com/stryker-mutator/stryker/issues/322) (Some people have worked on this using Git)

In my opinion, excluding the specific mutations would be the most important one for now as it's the most requested feature

**Comment by kmdrGroch** [comment] 2019-11-11 12:24
If I have enough time today, I'll fix it even today :)

**Comment by kmdrGroch** [comment] 2019-11-12 10:28
I think the most important now should be to update dependencies and fix type related errors (there are a lot of them) ._.. Please. We need this to be fixed asap. I have tried but I am not able to do it.

**Comment by kmdrGroch** [comment] 2019-11-13 14:33
Smaller topic, I would like to be fixed (From most important to least important):
- Update dependencies + fix issues related to that (#1589) [Its quite big chunk of things to repair, it might be needed to be done in several patches]
- change Promises into async functions (#1817) and related to it - slowly prepare to drop node 8 support (#1611) - since it's 13/11 and support ends on 31/12
- clean up docs (#1755), it's a big issue - even bigger discussion. but our documentation is really bad in some cases [tenths of issues about 'how to configure' or 'i can't test it', mostly comes to a misunderstanding of configuration]
 - discuss other rules in eslint and it's plugins - it's 'abstract' topic since there might be something that could be done or not. It is a long term issue. Just provide question/issue about some option and I'll find/fix it


--- minor/optional changes/features ---
- related to configuration - I am working on better CLI to setup the whole project (it's something like a combination of our current CLI and https://createapp.dev/). Along with updating docs, it should significantly improve UX.
- #1610 somethings like this could be considered to be implemented

**Comment by nicojs** [comment] 2020-04-20 18:56
@kmdrGroch we've started using the roadmap on our wiki page: https://github.com/stryker-mutator/stryker/wiki/Roadmap

Do you think this is a good place to put it? If you want something else up there, don't hesitate to respond 🌹

**Comment by nicojs** [comment] 2020-04-23 05:57
Closing this for now, please add a remark here if you think we need to do more (or open an issue)

**Closed by nicojs** 2020-04-23 05:57 UTC
