### ISSUE TITLE
Have to use "enableFindRelatedTests: false" for jest-runner to kill mutants 

### ISSUE THREAD

**Issue by candentira** [stryker-mutator/stryker#2147] opened 2020-04-14 21:50 UTC
Have to use "enableFindRelatedTests: false" for jest-runner to kill mutants - otherwise no tests are found for mutants and they all survive.

Using this option makes mutution testing to run much longer then without it. But without it result isn't correct - all mutants survive as no corresponding tests are found.

I've setup [smallest repo with TS, Jest and stryker setup](https://github.com/candentira/stryker-test) so that you could see the issue reproduced.

**Stryker config**

```js
module.exports = {
  $schema: 'https://raw.githubusercontent.com/stryker-mutator/stryker/master/packages/api/schema/stryker-core.json',
  mutator: 'typescript',
  packageManager: 'npm',
  reporters: [ 'html', 'clear-text', 'progress', 'dashboard' ],
  testRunner: 'jest',
  coverageAnalysis: 'off',
  jest: {
    config: require('./jest.config'),
    //next line is required for properly kill mutants - without it all survive
    enableFindRelatedTests: false
  },
  mutate: [
    'src/**/*.ts'
  ],
  thresholds: { high: 80, low: 60, break: null },
  maxConcurrentTestRunners: 2
}
```

**Test runner config (Jest.config.js)**

```
module.exports = {
  roots: ['test'],
  testEnvironment: 'node',
  transform: {
    '.(ts|tsx)': 'ts-jest',
  },
  testRegex: '(\\.(test|spec))\\.(ts|js)$',
  moduleFileExtensions: ['ts', 'tsx', 'js'],
  globals: {
    'ts-jest': {
      diagnostics: {
        pathRegex: '(\\.(test|spec))\\.(ts)$',
      },
    },
  },
};
```

**Stryker environment**

```
+-- @stryker-mutator/core@3.1.0
| +-- @stryker-mutator/api@3.1.0
| +-- @stryker-mutator/util@3.1.0
+-- @stryker-mutator/jest-runner@3.1.0
| +-- @stryker-mutator/api@3.1.0 deduped
+-- @stryker-mutator/typescript@3.1.0
| +-- @stryker-mutator/api@3.1.0 deduped
| +-- @stryker-mutator/util@3.1.0 deduped
```

```
@types/jest: 25.1.3,
jest: 25.1.0"
ts-jest: 25.2.1
```

**Test runner environment**

```shell
npm run mt
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v12.13.0
| npm              | 6.12.0
| Operating System | Windows 10

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker/files/4477933/stryker.log)

**Comment by nicojs** [comment] 2020-04-17 11:30
I guess this is a duplicate of #2122 . Could try one of the other workarounds reported here? https://github.com/stryker-mutator/stryker/issues/2122#issuecomment-605783668

**Comment by nicojs** [comment] 2021-01-25 14:05
You can also use the new [`--inPlace`](https://stryker-mutator.io/docs/stryker/configuration#inplace-boolean) mode, new since Stryker 4.4. Closing this issue for now, please open a new one if this problem persists.

**Closed by nicojs** 2021-01-25 14:05 UTC
Labels: 🐛 Bug
