### ISSUE TITLE
Running stryker using mocha and babel

### ISSUE THREAD

**Issue by RuudVerhoef** [stryker-mutator/stryker#1748] opened 2019-09-27 13:20 UTC
I am trying to run stryker using Mocha as a testrunner and Babel to be able to use the latest JS functions. Runnin only Mocha works fine but something seems to break when I try to run Stryker.
![aaa](https://user-images.githubusercontent.com/43232271/65772200-0b924980-e13a-11e9-8d06-ed90a0d4249f.png)
As you can see a lot of errors appear.
My stryker.con.js file looks like:
```
module.exports = function (config) {
  config.set({
    mutator: "javascript",
    packageManager: "npm",
    reporters: ["html", "clear-text", "progress"],
    testRunner: "mocha",
    transpilers: ["babel"],
    testFramework: "mocha",
    coverageAnalysis: "off",
    babel: {
      optionsFile: ".babelrc"
    },
    mochaOptions: {
      spec: ['tests/**/*.js'],
      require: ['@babel/register']
    },
    maxConcurrentTestRunners: 2
  });
};
```
And my package.json:
```
{
  "name": "my-Project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "nodemon --exec babel-node src/server.js",
    "test": "mocha --require @babel/register 'tests/**/**spec.js'",
    "report": "nyc --timeout=3000 --reporter=html npm test",
    "stryker": "npx stryker run"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^8.1.0",
    "express": "^4.17.1",
    "mongoose": "^5.7.1"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/node": "^7.6.2",
    "@babel/preset-env": "^7.6.2",
    "@babel/register": "^7.6.2",
    "@stryker-mutator/babel-transpiler": "^2.1.0",
    "@stryker-mutator/core": "^2.1.0",
    "@stryker-mutator/html-reporter": "^2.1.0",
    "@stryker-mutator/javascript-mutator": "^2.1.0",
    "@stryker-mutator/mocha-framework": "^2.1.0",
    "@stryker-mutator/mocha-runner": "^2.1.0",
    "chai": "^4.2.0",
    "mocha": "^6.2.0",
    "nodemon": "^1.19.2",
    "nyc": "^14.1.1",
    "sinon": "^7.5.0"
  },
  "nyc": {
    "all": true,
    "include": [
      "src/**/*.js"
    ]
  }
}
```
And finally the .babelrs file:
```
{
  "presets": ["@babel/preset-env"]
}
```

What am I doing wrong in setting up Stryker?

**Comment by kmdrGroch** [comment] 2019-09-27 14:20
Thx for your report. Could you please provide `log` file?

For now, we are supporting only some of the newest features. All of them will be available (as an user input) since #1623 is merged.

Features we support:
'asyncGenerators',
'bigInt',
'classProperties',
'dynamicImport',
'flow',
'jsx',
'objectRestSpread',
['decorators', { decoratorsBeforeExport: true }] as any,

**Comment by RuudVerhoef** [comment] 2019-09-28 10:16
What does this mean to me as an end user of Stryker? From what I understand, some features will be available soon as the branch you refered to is merged?

What is the method for generating a log file?

**Comment by kmdrGroch** [comment] 2019-09-28 11:35
add `fileLogLevel: 'debug'` to your stryker config, run stryker again, and post `stryker.log` file here.
But if it's really the matter of us lacking of features in babel config, then yes, unfortunately, you have to wait until that branch is merged.
the issue probably related to this: #1614

**Comment by kmdrGroch** [comment] 2019-11-13 18:05
@RuudVerhoef Now you should be able to fix this issue since #1764 was merged. Please give it a try :)

**Comment by kmdrGroch** [comment] 2020-08-19 13:25
@RuudVerhoef is it still an issue for you? I believe it has been fixed already :)
you can add babel plugins via mutator.plugins option

**Comment by kmdrGroch** [comment] 2020-10-02 17:12
I think it can be closed since there is no interest

**Comment by J-Verhoef** [comment] 2020-10-03 08:19
@kmdrGroch thanks for all the input. I've been busy running other projects that did not include Stryker and did not pay a lot of attention to the Github mails coming in noticing me of replies.

As far as I am concerned the issue is closed. I can no longer test if it has been solved in that specific project as I no longer have access to it.

**Comment by nicojs** [comment] 2020-10-07 05:50
Thanks @J-Verhoef , hope you're giving Stryker another try in the future 👍

**Closed by nicojs** 2020-10-07 05:50 UTC
Labels: ⁉ Question
