### ISSUE TITLE
Sometimes stryker do not exit at the end

### ISSUE THREAD

**Issue by sorokin-evgeni** [stryker-mutator/stryker#789] opened 2018-05-23 08:13 UTC
### Summary

Sometimes stryker do not exit at the end. It just print a report table.
It happen when I try to use parallelism (maxConcurrentTestRunners > 1).
In system monitoring I see few stryker subprocesses in such case.

### Stryker config

```js
module.exports = function(config){
  config.set({
{
        testRunner: 'jest',
        mutator: 'javascript',
        transpilers: ['babel'],
        reporter: ['clear-text', 'progress'],
        coverageAnalysis: 'off',
        logLevel: 'all',
        mutate: [
            'src/modules/*.js',
            '!src/**/*.spec.js'
        ],
        thresholds: { high: 80, low: 60, break: 60 },
        maxConcurrentTestRunners: 3,
        babelrcFile: '.babelrc'
    }
  });
}
```

### Stryker environment

```
    "stryker": "^0.23.0",
    "stryker-api": "^0.17.0",
    "stryker-babel-transpiler": "^0.5.0",
    "stryker-javascript-mutator": "^0.7.0",
    "stryker-jest-runner": "^0.7.0",
    "stryker-webpack-transpiler": "^0.4.0",
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             | 9.3.0
| npm              | 5.5.1
| Operating System |  MacOS 10.13.4

**Comment by simondel** [comment] 2018-05-23 08:31
Thanks for opening the issue! I see that you're using Jest. Do you have a Jest config? If so, where is it and what's in it? When you're using Jest you be able to run Stryker without a transpiler since Jest will do that for you.

**Comment by sorokin-evgeni** [comment] 2018-05-23 12:18
Here is a config:
```
{
  "verbose": true,
  "roots": [
    "src",
    "!dist/**/*",
    "!tests/**/*"
  ],
  "collectCoverage": true,
  "coverageDirectory": "coverage",
  "testResultsProcessor": "jest-teamcity-reporter"
}
```
It fails without a transpiller with the error: ```SyntaxError: Unexpected token import```.

**Comment by simondel** [comment] 2018-05-23 12:28
Alright, that doesn't seem to contain anything that stryker would need (since you have to tell stryker where your jest config is if you want to use it. See [configuring stryker-jest](https://github.com/stryker-mutator/stryker-jest-runner#configuring-jest)). For your regular development workflow you may want to take a look at [babel-jest](https://github.com/facebook/jest/tree/master/packages/babel-jest) if you always have to transpile your code before running your tests (won't fix the issue you're having though).

Would it be possible for you to make an application that can reproduce this issue? Perhaps you can take your current config and pretty much remove all your tests and source files.

**Comment by sorokin-evgeni** [comment] 2018-06-15 21:15
It is pretty hard to reproduce. Timeout 60000 helps me.

**Comment by nicojs** [comment] 2018-07-12 19:50
@sorokin-evgeni Could you try it again with the latest version of stryker (0.24.2)? We've recently implemented a fix where we now kill the entire child test process tree (instead of just the direct child). I've noticed that this was a problem in linux and mac in particular. If this was the cause, than it should be fixed now.

**Comment by simondel** [comment] 2018-08-12 12:51
As mentioned, we expect that the issue is resolved if you use the latest versions of Stryker. I'll close this issue for now. If it still persists, let us know!

**Closed by simondel** 2018-08-12 12:51 UTC
