### ISSUE TITLE
100% transpile errors = 0% coverage

### ISSUE THREAD

**Issue by riezebosch** [stryker-mutator/stryker#419] opened 2017-10-12 11:58 UTC
![screen shot 2017-10-12 at 13 57 31 1](https://user-images.githubusercontent.com/1427334/31494963-ddff9e72-af55-11e7-82f7-963e7fef5f77.png)

When the only possible mutation results in a transpile errors then there are no tests run. To my understanding these are not taken into account when calculating the coverage so the resulting coverage is 0%. I expect it to be 100%.

**Comment by nicojs** [comment] 2017-10-12 12:42
@riezebosch thabks for trying out the new typescript functionality. Indeed it is not used in calculation. However, if there are zero valid mutants, the score is calculated as 0. 

What would you expect as a score in this case?

**Comment by simondel** [comment] 2017-10-12 12:50
I would expect 💯 🥇

**Comment by nicojs** [comment] 2017-10-23 06:53
Not something like `n/a`?

**Comment by riezebosch** [comment] 2017-10-25 19:36
Or even more precise: `no mutants`

**Comment by nicojs** [comment] 2017-11-05 17:43
But there are mutants. Just not valid once. How about `no valid mutants`?

**Comment by Archcry** [comment] 2018-05-18 09:54
![screenshot_20180518_115313](https://user-images.githubusercontent.com/1557855/40228668-31f7f7d0-5a92-11e8-8234-c19e50cc02a4.png)

I am no longer able to reproduce the issue, test repo at https://github.com/Archcry/stryker-calculate-score-example

**Comment by nicojs** [comment] 2018-05-18 09:56
Thats because you have 1 mutant. It has state `TranspileError`. Thus 100%

**Comment by Archcry** [comment] 2018-05-18 11:05
>Thats because you have 1 mutant. It has state TranspileError. Thus 100%
Yes, but it's the same as the example given in the first post.

**Comment by nicojs** [comment] 2018-05-18 11:11
Hmm true. I think we might have implemented it without closing this issue. I'll close it for now, feel free to reopen or comment here if it is not fixed.

**Closed by nicojs** 2018-05-18 11:11 UTC
Labels: bug, needs review
