### ISSUE TITLE
Cannot read property 'runResult' of undefined 

### ISSUE THREAD

**Issue by sugandhgoyal** [stryker-mutator/stryker#359] opened 2017-08-18 08:22 UTC
Below is my stryker.conf.js-
```js
module.exports = function(config) {
    config.set({
        "files": [{
                "pattern": "src/**/*.js",
                "mutated": true,
                "included": false
            },
            "test/**/*.js"
        ],
        "testRunner": "mocha",
        "reporter": [
            "clear-text",
            "progress"
        ],
        "testFramework": "mocha",
        "coverageAnalysis": "perTest"
    });
}
```
My file structure is as follows

.stryker-tmp
 node-modules
 src
    index.js
 test
    index.js
 package.json
 stryker.conf.js

**Comment by nicojs** [comment] 2017-08-21 06:33
Thanks for reporting this issue. Could you please verify with `logLevel: debug` that your test files are listed on your screen? If not, i think this is a duplicate of #347.

Basically: stryker gives this error whenever no tests could be found using the stryker-mocha-runner.

**Comment by simondel** [comment] 2017-08-25 14:19
Hi! We fixed the original error so the issue has been closed. Please upgrade to:

 - stryker-api@0.8.0
 - stryker-mocha-framework@0.4.0
 - stryker-mocha-runner@0.7.0
 - stryker@0.9.0

**Closed by simondel** 2017-08-25 14:19 UTC
