### ISSUE TITLE
One or more tests errorred in the initial test run

### ISSUE THREAD

**Issue by chrabia** [stryker-mutator/stryker#142] opened 2016-08-12 09:15 UTC
Hello, 
I have a problem with stryker. I installed it (with stryker-karma-runner and some other plugins), but when I run it then I have above error (even though, of course, my tests are passing).
This is my stryker.conf.js:

``` js
module.exports = function(config){
    config.set({
        files: [<same files I am providing in karma.conf.js>],
        mutate: ['src/**/*.js'],
        testFramework: 'jasmine',
        testRunner: 'karma',
        logLevel: 'debug',
        reporter: 'html',
        htmlReporter: {
            baseDir: 'results/mutation/html'
        }
    });
};
```

**Comment by chrabia** [comment] 2016-08-12 09:17
Exact error:
One or more tests errored in the initial test run:
        TypeError: undefined is not an object (evaluating '__cov_7rAeJca4OC$XFNXK8gjrXg.s['2']')
at http://localhost:9234/base/src/<path-to-my-file>?cca4654f7e332a6772ca2e24916edea15e308678:9

I tried changing logging level from debug to trace, but it didn't provide me with any interesting information.

**Comment by nicojs** [comment] 2016-08-12 09:22
Hi chrabia, thanks for the issue! Seeing the output with logLevel trace, i think the issue has to do with code coverage. 

Could you provide us with information about your installed npm modules? `npm ls` should do the trick. Also, could you add the karma config stryker is using? It should be logged with level `trace` as well, starting with `using config:`.

**Comment by chrabia** [comment] 2016-08-12 10:41
The list is with npm ls is very long, so I'm adding a file with it:
[npm-modules.txt](https://github.com/stryker-mutator/stryker/files/415126/npm-modules.txt)

karma config:
{"browsers": ["PhantomJS"], "frameworks": ["jasmine"], "autoWatch": false, "singleRun": false, "detached": false, "files": <some project files>, "port": 9234, "coverageReporter": {
        "type": "in-memory"
    },
    "preprocessors": <some project files>,
    "reporters": ["coverage"]
}

Btw. I tried to use stryker in another project and it worked, so maybe you're right about some wrong configuration of my npm modules.

**Comment by nicojs** [comment] 2016-08-12 10:50
Hmm the "preprocessors" value is left out. Did you remove them by any chance? I remember i had the same error once. The problem was that the files array had some source files twice. Karma can handle such situations, but the `stryker-karma-runner` configures the file in question to be preprocessed *twice* by the `"coverage"` preprocessor, resulting in double code coverage instrumentation and, eventually, into the TypeError.

Can this indeed be the case?

**Comment by chrabia** [comment] 2016-08-12 11:06
No, it's not the case, sorry, github changed my "some-project-files" to an empty string.

**Comment by nicojs** [comment] 2016-08-12 11:16
Could you please provide me with the entire log line? Without it, its kind of hard to debug this issue. If you don't want to share your config with the entire world, you can also send it as a private message on twitter @_nicojs

You can also debug it yourself by reproducing the issue with Karma. Using the karma conf on the log line of stryker. Of course Stryker works on temp files, which it cleans after the test run. If you kill the stryker process at the right moment in time, the temp files will still exist.

**Comment by chrabia** [comment] 2016-08-12 13:38
A few interesting facts: 

First:
I think that this is needed in my karmaConfig in stryker.conf.js:
```js
preprocessors: {
            "src/**/*.js": "coverage",
            "src/**/*.html": ["ng-html2js"]
        },

        ngHtml2JsPreprocessor: {
            moduleName: "ngHtml2JsTemplates"
        }
```



Second: why is it that when I comment "mutate" from my stryker config then running stryker takes so long? (3-4 minutes, when my unit tests normally takes like 3-4 seconds)



Third: when i run stryker without mutate and with karmaConfig described above I following problem:

[2016-08-12 14:55:02.869] [DEBUG] TestRunnerOrchestrator - Creating test runner 0 using settings {port: 9234, coverageEnabled: true}

<--- Last few GCs --->

 1168652 ms: Mark-sweep 1396.6 (1457.0) -> 1397.8 (1457.0) MB, 1209.8 / 0 ms [allocation failure] [GC in old space requested].
 1169835 ms: Mark-sweep 1397.8 (1457.0) -> 1397.8 (1457.0) MB, 1183.6 / 0 ms [allocation failure] [GC in old space requested].
 1171059 ms: Mark-sweep 1397.8 (1457.0) -> 1396.5 (1457.0) MB, 1224.2 / 0 ms [last resort gc].
 1172259 ms: Mark-sweep 1396.5 (1457.0) -> 1397.8 (1457.0) MB, 1198.8 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000008F05E37349 <JS Object>
    1: parse [native json.js:~40] [pc=0000000D231DA4C3] (this=0000008F05E38161 <a JSON with map 000000E2E13163D1>,r=000003DBC1E0EBE1 <Very long string[532608]>,l=0000008F05E04131 <undefined>)
    2: arguments adaptor frame: 1->2
    3: onread [internal/child_process.js:~422] [pc=0000000D243CF513] (this=0000038363E282F1 <a Pipe with map 0000012CC8949DD9>,nread=532609,pool=000003DBC1E0EC09 <an ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

**Comment by nicojs** [comment] 2016-09-05 06:01
Sorry for the long wait.

For your first observation: you indeed need to supply the `ng-html2js` as preprocessor if you need it.  However, you should remove this line: `"src/**/*.js": "coverage"` as that will result in the double instrumentation. Stryker will add the instrumentation if it needs it.


I created an issue for your second observation as i've been able to reproduce it locally: #147

**Comment by nicojs** [comment] 2016-09-06 05:22
Hi @chrabia , i just tested stryker with a karma preprocessor and indeed it makes the test unreliable. I created an issue for it: #148 

I realize that i didn't explain the reason for the slow tests yet. The reason is that Stryker tries to analyze the code to see exactly which tests covers which lines of code (or statements to be exact). That way, when a statement is mutated, only the tests are ran that actually cover that statement. 

This can drastically improve the performance of stryker in a large set of tests. In general, you will have a lot of mutants to test. If you would have to do a 4 sec test run on each, it would take a lot of time, even with the parallelization (spinning up multiple test runners) we already do. If you could reduce that to just a few tests, it can be done in <0.5 sec. Much more reasonable.

The way the analysis works right now is: select 1 test, run karma, use karma-coverage to report coverage, select next test, run karma, etc. This is not yet parallelized, so if you have 100's of tests, it takes a while. The out-of-memory error is a result of this i think, but i don't know the exact cause. 

I'm thinking of better ways to do the code analysis. Ideally you would want only one pass of karma to be enough. You could for example use the `beforeEach` and `afterEach` hooks to report and clear the global code coverage object. 

For now; you could try to disable the coverage analysis with setting the testSelector to null `testSelector: null` in your stryker.conf.js. but first: this issue needs to be fixed: #148 . I'll be working on that one later this week.

**Comment by chrabia** [comment] 2016-11-08 09:06
Hi there,
I tried again (I removed preprocessors and tests that were using it) and I found another problem.
When I tried to set testSelector: null then I got this:

```
[2016-11-08 09:57:06.818] [INFO] Stryker - 3164 Mutant(s) generated
[2016-11-08 09:57:06.904] [INFO] TestRunnerOrchestrator - Creating 4 test runners (based on cpu count)
[2016-11-08 09:57:06.910] [DEBUG] TestRunnerOrchestrator - Creating a sandbox for files in path-to-project\.stryker-tmp\6610125\test-runner-files8301729
[2016-11-08 09:57:07.453] [DEBUG] TestRunnerOrchestrator - Creating a sandbox for files in path-to-project\.stryker-tmp\6610125\test-runner-files225819
[2016-11-08 09:57:07.998] [DEBUG] TestRunnerOrchestrator - Creating a sandbox for files in path-to-project\.stryker-tmp\6610125\test-runner-files1249111
[2016-11-08 09:57:08.502] [DEBUG] TestRunnerOrchestrator - Creating a sandbox for files in path-to-project\.stryker-tmp\6610125\test-runner-files1055233
Fatal error: Stryker was unable to run the mutation test
```

I checked files in ```.stryker-tmp``` and in every ```test-runner-files-number``` there are all files that I provided  as ```files``` to stryker, but all of them are empty, 0 bytes.
Is this how it should behave?

**Comment by simondel** [comment] 2018-01-10 19:46
Hi! Sorry for the incredibly slow response. Are you still interested in Stryker? If so, could you test if the latest version of Stryker (and the plugins) fix things for you?

**Comment by nicojs** [comment] 2018-04-20 07:37
Closing this issue for now. If you still experience this problem with the latest release, please open a new issue.

**Closed by nicojs** 2018-04-20 07:37 UTC
Labels: question
