### ISSUE TITLE
Support for environment variables for mutant runs

### ISSUE THREAD

**Issue by CrazyBS** [stryker-mutator/stryker#693] opened 2018-04-11 18:01 UTC
### Summary

**Feature Request**: I'd like to support adding environment variables for the mutant runners to use.  For my specific situation, I needed to add the variable `NODE_PATH` on my command line and I tried to do that by running `NODE_PATH=... stryker run`.

When I used the command to execute my tests, the initial test run worked exactly as expected, but during the mutant runs ALL of my tests failed because the path wasn't set correctly in the runners.  The result was that stryker thought ALL of my mutants were killed and I got 100% coverage.  This is not true at all.  I proved this by hardcoding path resolution into my test suite to not rely on the NODE_PATH and got much more realistic mutation results.   I can't leave the hardcoded paths because it needs to be dynamic in my use case.

**Uncovered Bug**:  I would expect the mutation runners to be working in the same environment as the initial test run is in.  In order to have a correct base line, all conditions need to be the same, including the environment variables.

### Stryker config

```js
module.exports = function (config) {
    config.set({
        files: [
            { pattern: 'XXX/**/*.js', mutated: true, included: false },
            { pattern: 'test/**/*.js', included: true, mutated: false },
            { pattern: 'XXX/**/*.json', included: false, mutated: false },
            { pattern: 'test/**/*.json', included: false, mutated: false },
        ],
        testRunner: 'mocha',
        mutator: 'javascript',
        transpilers: [],
        reporter: ['html', 'clear-text', 'progress'],
        testFramework: 'mocha',
        coverageAnalysis: 'all',
        thresholds: { high: 80, low: 60, break: 60 },
        htmlReporter: { baseDir: 'build/mutation' }
    });
};
```

### Stryker environment

```
+-- stryker@0.18.0
+-- stryker-api@0.12.0
+-- stryker-javascript-mutator@0.3.2
+-- stryker-mocha-runner@0.10.2
+-- stryker-mocha-framework@0.8.0
+-- stryker-html-reporter@0.11.4
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             | v6.11.3
| npm              | 5.8.0
| Operating System | MacOS 10.12.6

**Comment by simondel** [comment] 2018-04-14 06:05
@CrazyBS Thanks for making us aware of this! I find it quite strange because Stryker runs all test runs in the same type of sandbox so the environment should be the same. So I would expect Stryker to either always fail or never fail.

Adding environment variables to the stryker config sounds like a good idea. What are your thoughts on this @stryker-mutator/stryker-core ?

**Comment by nicojs** [comment] 2018-04-16 15:17
> When I used the command to execute my tests, the initial test run worked exactly as expected, but during the mutant runs ALL of my tests failed because the path wasn't set correctly in the runners. 

That would be an actual bug. The path should be the same in all test runner processes.

>  I would expect the mutation runners to be working in the same environment as the initial test run is in. In order to have a correct base line, all conditions need to be the same, including the environment variables.

I totally agree. Apart from code coverage and source-map settings, everything should be the same.

**Comment by nicojs** [comment] 2018-04-20 15:05
@CrazyBS I've tried to reproduce it (first I had to read up on the NODE_PATH environment variable, I was clueless you could do something like that). 

See this repository: https://github.com/nicojs/stryker-node_path-test I don't have any issue with NODE_PATH. When using `NODE_PATH=./shared stryker run` everything works fine.

```
git clone git@github.com:nicojs/stryker-node_path-test.git
cd stryker-node_path-test
npm i
npm t
```

Running the tests with mocha and running stryker with the mocha test runner both work as expected. Could you try to reproduce your issues in this repo? Thanks a lot!

**Comment by nicojs** [comment] 2018-05-11 07:17
@CrazyBS in order to keep our issues tidy, we will close this in 2 weeks if we don't hear from you.

**Comment by nicojs** [comment] 2018-07-08 19:07
We're closing it for now. Please create a new issue if the problem persists.

**Closed by nicojs** 2018-07-08 19:07 UTC
Labels: comitted, feature
