### ISSUE TITLE
Could not transpile input files: Execute babel: ... Cannot read property 'useBuiltIns' of undefined

### ISSUE THREAD

**Issue by yuri-sakharov** [stryker-mutator/stryker#607] opened 2018-02-06 17:15 UTC
### Summary

Hi,
I trying to add stryker to our project. I did `./node_modules/.bin/stryker init ` , after added one test file to config and run `./node_modules/.bin/stryker run` 
got error error:
```
[2018-02-06 19:01:35.395] [INFO] BabelConfigReader - Reading .babelrc file from path "/Users/yuri/repos/v3/.babelrc"
[2018-02-06 19:01:35.556] [ERROR] StrykerCli - an error occurred Error: Could not transpile input files: Execute babel: /Users/yuri/repos/v3/app/actions/unit-tests/app-state-spec.js: Cannot read property 'useBuiltIns' of undefined
    at InitialTestExecutor.<anonymous> (/Users/yuri/repos/v3/node_modules/stryker/src/process/InitialTestExecutor.js:54:31)
    at step (/Users/yuri/repos/v3/node_modules/tslib/tslib.js:133:27)
    at Object.next (/Users/yuri/repos/v3/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/Users/yuri/repos/v3/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
```
attached [error.log](https://github.com/stryker-mutator/stryker/files/1700037/error.log)

but when I run via `NODE_ENV=test ./node_modules/.bin/stryker run`
got:
```
[2018-02-06 22:02:23.396] [INFO] BabelConfigReader - Reading .babelrc file from path "/Users/yuri/repos/v3/.babelrc"
[2018-02-06 22:02:23.546] [ERROR] StrykerCli - an error occurred Error: Could not transpile input files: Execute babel: /Users/yuri/repos/v3/app/actions/unit-tests/app-state-spec.js: Cannot read property 'loose' of undefined
    at InitialTestExecutor.<anonymous> (/Users/yuri/repos/v3/node_modules/stryker/src/process/InitialTestExecutor.js:54:31)
    at step (/Users/yuri/repos/v3/node_modules/tslib/tslib.js:133:27)
    at Object.next (/Users/yuri/repos/v3/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/Users/yuri/repos/v3/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
```
attached [error2.log](https://github.com/stryker-mutator/stryker/files/1700635/error2.log)

### Stryker config
```
module.exports = function (config) {
    config.set({
        files: [
            "./app/actions/unit-tests/app-state-spec.js",
        ],
        testRunner: "mocha",
        mochaOptions: {
            require: ['test/init.js', 'test/mocha.env.js'],
        },
        mutator: "javascript",
        transpilers: ["babel"],
        reporter: ["html", "clear-text", "progress"],
        testFramework: "mocha",
        coverageAnalysis: "off",
        babelrcFile: ".babelrc",
        logLevel: 'debug',
    });
};

```

### Stryker environment

```
├─┬ stryker@0.18.2
├─┬ stryker-api@0.12.0
├─┬ stryker-babel-transpiler@0.2.4
├─┬ stryker-html-reporter@0.11.5
├─┬ stryker-javascript-mutator@0.3.3
├─┬ stryker-mocha-framework@0.8.1
├─┬ stryker-mocha-runner@0.10.3

    "@babel/core": "7.0.0-beta.39",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.39",
    "@babel/plugin-syntax-object-rest-spread": "7.0.0-beta.39",
    "@babel/plugin-transform-arrow-functions": "7.0.0-beta.39",
    "@babel/plugin-transform-modules-commonjs": "7.0.0-beta.39",
    "@babel/preset-env": "7.0.0-beta.39",
    "@babel/preset-react": "7.0.0-beta.39",
    "@babel/register": "7.0.0-beta.39",
    "app-module-path": "2.2.0",
    "autoprefixer": "7.2.5",
    "babel-core": "^6.26.0",
    "babel-loader": "8.0.0-beta.0",
    "babel-plugin-istanbul": "4.1.5",
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             | v9.4.0
| npm              | 5.6.0
| Operating System | Mac OS Sierra v10.12.6

**Comment by nicojs** [comment] 2018-02-07 07:30
@yuri-sakharov thanks for reporting this issue. I don't know exactly where `useBuiltIns` comes from, but it might be because you have an empty sandbox (apart from `"./app/actions/unit-tests/app-state-spec.js"`). The idea of the `files` array is that you specify all files you need for testing. These should include all needed source code, as well as your mocha require files: 'test/init.js', 'test/mocha.env.js'.

Could you try again with those files included?

**Comment by yuri-sakharov** [comment] 2018-02-07 09:21
@nicojs thank you for response. I tried with this:
```
module.exports = function (config) {
    config.set({
        files: [
            'test/init.js',
            'test/mocha.env.js',
            './app/**/*-spec.js',
           { pattern: './app/**/*.*', included: false, mutated: false },
        ],
        testRunner: "mocha",
        mochaOptions: {
            require: ['test/init.js', 'test/mocha.env.js'],
        },
        mutator: "javascript",
        transpilers: ["babel"],
        reporter: ["html", "clear-text", "progress"],
        testFramework: "mocha",
        coverageAnalysis: "off",
        babelrcFile: ".babelrc",
        logLevel: 'debug',
    });
};
```
and still got `/Users/yuri/repos/v3/app/views/workspaces/dashboard/recent-usage.js: Cannot read property 'useBuiltIns' of undefined` for all files.

I found 'useBuiltIns' in `.babelrc` file 
```
...
},
        "development": {
            "plugins": [
                "react-hot-loader/babel",
                "@babel/plugin-proposal-object-rest-spread"
            ],
            "presets": [
                "@babel/preset-react",
                [
                    "@babel/preset-env",
                    {
                        "debug": false,
                        "modules": false,
                        "useBuiltIns": "usage"
                    }
                ]
            ]
        },
        "production": {
...
```

**Comment by nicojs** [comment] 2018-02-07 14:25
@Archcry could you take a look at this one? It seems to do with .babelrc settings.

**Comment by Archcry** [comment] 2018-02-08 10:15
What I notice is that you have an array of presets defined in your babelrc, you specify one preset and then define another array in which you define the other. I don't think it will work this way and that might also be the reason why buildIns aren't working.

Could you try the following babelrc:
```
...
},
        "development": {
            "plugins": [
                "react-hot-loader/babel",
                "@babel/plugin-proposal-object-rest-spread"
            ],
            "presets": [
                "@babel/preset-react",
                "@babel/preset-env",
                {
                    "debug": false,
                    "modules": false,
                    "useBuiltIns": "usage"
                }
            ]
        },
        "production": {
...

**Comment by Archcry** [comment] 2018-02-08 10:34
Hmm I don't see the problem either. It should just use the options provided in the babelrc when transforming the code in the babel transpiler. And the babelrc works for his project. What I find odd is when he changes the environment to test he gets another error.

**Comment by nicojs** [comment] 2018-02-08 10:41
Its the same error with a different property name. Can you try to reproduce it? If you can, maybe you van debug to see what object is undefined, that should hep is figure out why.

**Comment by yuri-sakharov** [comment] 2018-02-08 10:54
I tried now:
`NODE_ENV=stryker ./node_modules/.bin/stryker run`
in .babelrc:
 ```
"stryker": {
      "only": [
        "app/actions",
        "app/collections",
        "app/components",
        "app/config",
        "app/constants",
        "app/executive-summary",
        "app/helpers",
        "app/login",
        "app/middleware",
        "app/mocks",
        "app/models",
        "app/recorder",
        "app/reducers",
        "app/statics",
        "app/store",
        "app/views",
        "app/main.js"
      ],
      "plugins": [
        "react-hot-loader/babel",
        "@babel/plugin-proposal-object-rest-spread"
      ],
      "presets": [
        "@babel/preset-react",
        "@babel/preset-env"
      ]
    }
```
and still got 
```
Cannot read property 'useBuiltIns' of undefined
    at InitialTestExecutor.<anonymous> (/Users/yuri/repos/v3/node_modules/stryker/src/process/InitialTestExecutor.js:54:31)
    at step (/Users/yuri/repos/v3/node_modules/tslib/tslib.js:133:27)
    at Object.next (/Users/yuri/repos/v3/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/Users/yuri/repos/v3/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
```

**Comment by simondel** [comment] 2019-02-13 13:57
Since Stryker has changed a lot in the past year, I'm closing this issue right now. If you still have the issue with the latest version of Stryker (`@stryker-mutator/core^1.0.0`), please let us know!

**Closed by simondel** 2019-02-13 13:57 UTC
Labels: question
