### ISSUE TITLE
Beta: Stryker can get confused by its own reports directory

### ISSUE THREAD

**Issue by gramster** [stryker-mutator/stryker#2466] opened 2020-09-09 15:33 UTC
**Question**

I'm making this a question for now but perhaps it should be labelled a bug. I'm using the beta, and worked around the issue https://github.com/stryker-mutator/stryker/issues/2465 for now, but now after instrumentation nothing happens. I have detailed logging on, and I left it running for hours, but the last thing in the log is:

```
$ npx stryker run --fileLogLevel trace --logLevel debug
...
21:32:56 (23497) DEBUG Instrumenter Instrumented src/client/workspaceSymbols/parser.ts (120 mutant(s))
21:32:56 (23497) DEBUG Instrumenter Instrumented src/client/workspaceSymbols/provider.ts (33 mutant(s))
21:32:56 (23497) INFO Instrumenter Instrumented 768 source file(s) with 48482 mutant(s)
```

and nothing happens after that.

Config:

```
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "packageManager": "npm",
  "reporters": [
    "html",
    "clear-text",
    "progress"
  ],
  "testRunner": "mocha",
  "buildCommand": "npx gulp prePublishNonBundle",
  "mutate": ["src/client/**/*.ts"],
  "coverageAnalysis": "perTest"
}
```

This is for the [Python extension for Visual Studio Code](https://github.com/microsoft/vscode-python), so it should be reproducable.

It's very possible that my configuration is not right, but I still wouldn't expect a hang like this.

**Stryker environment**

```
├─┬ UNMET PEER DEPENDENCY @stryker-mutator/core@4.0.0-beta.4
│ ├─┬ @stryker-mutator/api@4.0.0-beta.4
│ ├─┬ @stryker-mutator/instrumenter@4.0.0-beta.4
│ │ ├─┬ @stryker-mutator/api@4.0.0-beta.4
│ │ ├─┬ @stryker-mutator/util@4.0.0-beta.4
│ ├─┬ @stryker-mutator/util@4.0.0-beta.4
├── @stryker-mutator/javascript-mutator@4.0.0-beta.4
├─┬ @stryker-mutator/mocha-framework@3.3.1
│ ├─┬ @stryker-mutator/api@3.3.1
│ └── @stryker-mutator/util@3.3.1
├─┬ @stryker-mutator/mocha-runner@4.0.0-beta.4
│ ├─┬ @stryker-mutator/api@4.0.0-beta.4
│ ├─┬ @stryker-mutator/util@4.0.0-beta.4
├── @stryker-mutator/typescript@4.0.0-beta.4
├─┬ @stryker-mutator/typescript-checker@4.0.0-beta.4
│ ├─┬ @stryker-mutator/api@4.0.0-beta.4
│ ├─┬ @stryker-mutator/util@4.0.0-beta.4
├─┬ @stryker-mutator/webpack-transpiler@3.3.1
│ ├── @stryker-mutator/api@3.3.1 deduped
```

```
├── @types/mocha@5.2.7
```

**Additional context**

I haven't added any config for the typescript checker as the build command makes use of multiple tsconfig files for different parts of the code.

**Comment by kmdrGroch** [comment] 2020-09-09 17:12
check for sure if you have good packages, i can see some 3.3.1 versions here. + i think we are not using transpilers now (i dunno if it beta.4 tho). Also please provide full stryker.log file :)

**Comment by gramster** [comment] 2020-09-09 17:24
I pointed you to the repo I am running against, which together with the config file is everything you would need to repro (except for bug 2465, which I had to work around - the modified repo is at this fork/branch: https://github.com/gramster/vscode-python-me/tree/stryker). I can see that the Stryker process is still consuming CPU but I don't know what it is doing. Full log file is too large to attach but I don't think it will tell you anything more useful than what I posted above. Some of the old packages are there because I started with Stryker 3 and then switched to beta; I don't think they should have any impact but I can remove them.

**Comment by gramster** [comment] 2020-09-09 18:02
I removed all the Stryker packages and then ran:

```
npm install --save-dev @stryker-mutator/core@next @stryker-mutator/mocha-framework@next @stryker-mutator/mocha-runner@next @stryker-mutator/typescript-checker@nex
```

which resulted in:

```
➜  vscode-python-me git:(stryker) ✗ npm ls | grep stryker
├─┬ UNMET PEER DEPENDENCY @stryker-mutator/core@4.0.0-beta.4
│ ├─┬ @stryker-mutator/api@4.0.0-beta.4
│ ├─┬ @stryker-mutator/instrumenter@4.0.0-beta.4
│ │ ├─┬ @stryker-mutator/api@4.0.0-beta.4
│ │ ├── @stryker-mutator/util@4.0.0-beta.4 deduped
│ ├─┬ @stryker-mutator/util@4.0.0-beta.4
├── @stryker-mutator/javascript-mutator@4.0.0-beta.4
├─┬ @stryker-mutator/mocha-framework@4.0.0-beta.4
│ ├─┬ @stryker-mutator/api@4.0.0-beta.4
│ └── @stryker-mutator/util@4.0.0-beta.4 deduped
├─┬ @stryker-mutator/mocha-runner@4.0.0-beta.4
│ ├─┬ @stryker-mutator/api@4.0.0-beta.4
│ ├── @stryker-mutator/util@4.0.0-beta.4 deduped
├── @stryker-mutator/typescript@4.0.0-beta.4
├─┬ @stryker-mutator/typescript-checker@4.0.0-beta.4
│ ├─┬ @stryker-mutator/api@4.0.0-beta.4
│ ├── @stryker-mutator/util@4.0.0-beta.4 deduped
├─┬ @stryker-mutator/webpack-transpiler@3.3.1
│ ├─┬ @stryker-mutator/api@3.3.1
```

and stryker still gets stuck.

**Comment by gramster** [comment] 2020-09-09 18:30
I broke in with a debugger and got this call stack: 

![image](https://user-images.githubusercontent.com/2762632/92638457-26989380-f28f-11ea-9e31-5a24f85c4acc.png)

It turned out it was stuck trying to process files created by Stryker itself in the reports/ directory. After deleting that folder it started making progress again. Stryker should probably be ignoring that directory.

**Comment by nicojs** [comment] 2020-09-09 20:02
Awesome work you're doing here @gramster This is helping us a lot 🎉 

> It turned out it was stuck trying to process files created by Stryker itself in the reports/ directory. After deleting that folder it started making progress again. Stryker should probably be ignoring that directory.

I _think_ this is a bit "by design" 😅 . We're currently using your own `.gitignore` file to ignore the files you're ignoring in your project. So we _assume_ you're putting `reports` in your ignore file. Maybe we should add it during init.

As for the `strip comments` preprocessor. It's actually a bug that is already fixed, but we didn't release a new version of the beta. Let me do that right now, currious to see if that fixes a lot of issues you're having

**Comment by nicojs** [comment] 2020-09-17 13:37
@gramster I think this can be closed, or is there still something to be done here?

**Comment by nicojs** [comment] 2020-09-22 07:06
Closing this for now. Don't hesitate to contact me if you think it is a mistake 👍

**Closed by nicojs** 2020-09-22 07:06 UTC
Labels: 🐛 Bug
