### ISSUE TITLE
Ability to disable some mutators

### ISSUE THREAD

**Issue by unlight** [stryker-mutator/stryker#293] opened 2017-04-26 08:35 UTC
Atm, stryker does not work with TypeScript, I need intermediate step to compiler ts source to at least to ES6.

Stryker mangles decorators which leads to guaranteed runtime exception.
Obviously, it is not very useful mutants.

```
-   FeatureRoutingModule = tslib_1.__decorate([
-       core_1.NgModule({
-           imports: [router_1.RouterModule.forChild(featureRoutes)],
-           exports: [router_1.RouterModule]
-       })
-   ], FeatureRoutingModule);
+   FeatureRoutingModule = tslib_1.__decorate([], FeatureRoutingModule);
```

**Comment by nicojs** [comment] 2017-04-26 17:09
True. We're working on native TypeScript support behind the scenes but it will take some. 

In the mean time you might want to enable the `importHelpers` compiler flag. That would already help you quite a lot by minimizing the boiler plate code it would normally emit. But the example you give would still be there.

How would you like the disabling of mutators to work? Have a `disabledMutators` flag in the config? Every mutator has a name, in your example it is the ["ArrayDeclarator"] (https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/src/mutators/ArrayDeclaratorMutator.ts)

It could look like this:

```javascript
{
  disabledMutators: [
   'ArrayDeclarator',
   'BinaryOperator'
}
```

Its important to note that errors during mutation testing are reported separately as type `error`, which do not impact the mutation score (as explained in the [FAQ](http://stryker-mutator.github.io/faq.html))

**Comment by shybyte** [comment] 2017-12-15 08:55
This feature request seems to be a duplicate of #13.

**Comment by nicojs** [comment] 2017-12-18 16:03
Duplicate of #13 (thanks @shybyte )

**Closed by nicojs** 2017-12-18 16:03 UTC
Labels: feature
