### ISSUE TITLE
jest-runner is not working with even a simple project

### ISSUE THREAD

**Issue by tylermurry** [stryker-mutator/stryker#2071] opened 2020-03-03 17:25 UTC
**Summary**

I am trying to include Stryker into a project that uses Jest, but I'm running up against problems with even the simplest of projects. To demonstrate this, I have created a dead-simple node project that uses Jest and generates the following issue:

* Repo: https://github.com/tylermurry/stryker-jest-runner-issues-2071

```sh
11:12:27 (16352) INFO ConfigReader Using stryker.conf.js in the current working directory.
11:12:28 (16352) WARN InputFileResolver No files marked to be mutated, Stryker will perform a dry-run without actually mutating anything. You can configure the `mutate` property in your stryker.conf.js file (or use `--mutate` via command line).
11:12:28 (16352) INFO InitialTestExecutor Starting initial test run. This may take a while.
11:12:31 (16352) WARN Sandbox Could not symlink "/Users/dev/stryker-test/node_modules" in sandbox directory, it is already created in the sandbox. Please remove the node_modules from your sandbox files. Alternatively, set `symlinkNodeModules` to `false` to disable this warning.
11:12:36 (16352) ERROR InitialTestExecutor One or more tests resulted in an error:
        Test runner crashed. Tried twice to restart it without any luck. Last time the error message was: Error: TypeError: Cannot read property 'runCLI' of undefined
TypeError: Cannot read property 'runCLI' of undefined
    at JestPromiseTestAdapter.run (/Users/dev/stryker-test/node_modules/@stryker-mutator/jest-runner/src/jestTestAdapters/JestPromiseTestAdapter.js:17:31)
    at JestTestRunner.run (/Users/dev/stryker-test/node_modules/@stryker-mutator/jest-runner/src/JestTestRunner.js:43:56)
    at ChildProcessTestRunnerWorker.run (/Users/dev/stryker-test/node_modules/@stryker-mutator/core/src/test-runner/ChildProcessTestRunnerWorker.js:24:56)
    at ChildProcessProxyWorker.doCall (/Users/dev/stryker-test/node_modules/@stryker-mutator/core/src/child-proxy/ChildProcessProxyWorker.js:75:56)
    at resolve (/Users/dev/stryker-test/node_modules/@stryker-mutator/core/src/child-proxy/ChildProcessProxyWorker.js:46:53)
    at new Promise (<anonymous>)
    at ChildProcessProxyWorker.handleMessage (/Users/dev/stryker-test/node_modules/@stryker-mutator/core/src/child-proxy/ChildProcessProxyWorker.js:46:17)
    at process.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Error: TypeError: Cannot read property 'runCLI' of undefined
TypeError: Cannot read property 'runCLI' of undefined
    at JestPromiseTestAdapter.run (/Users/dev/stryker-test/node_modules/@stryker-mutator/jest-runner/src/jestTestAdapters/JestPromiseTestAdapter.js:17:31)
    at JestTestRunner.run (/Users/dev/stryker-test/node_modules/@stryker-mutator/jest-runner/src/JestTestRunner.js:43:56)
    at ChildProcessTestRunnerWorker.run (/Users/dev/stryker-test/node_modules/@stryker-mutator/core/src/test-runner/ChildProcessTestRunnerWorker.js:24:56)
    at ChildProcessProxyWorker.doCall (/Users/dev/stryker-test/node_modules/@stryker-mutator/core/src/child-proxy/ChildProcessProxyWorker.js:75:56)
    at resolve (/Users/dev/stryker-test/node_modules/@stryker-mutator/core/src/child-proxy/ChildProcessProxyWorker.js:46:53)
    at new Promise (<anonymous>)
    at ChildProcessProxyWorker.handleMessage (/Users/dev/stryker-test/node_modules/@stryker-mutator/core/src/child-proxy/ChildProcessProxyWorker.js:46:17)
    at process.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at ChildProcess.worker.on (/Users/dev/stryker-test/node_modules/@stryker-mutator/core/src/child-proxy/ChildProcessProxy.js:133:68)
    at ChildProcess.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
11:12:36 (16352) ERROR StrykerCli an error occurred Error: Something went wrong in the initial test run
    at InitialTestExecutor.validateResult (/Users/dev/stryker-test/node_modules/@stryker-mutator/core/src/process/InitialTestExecutor.js:86:15)
    at InitialTestExecutor.run (/Users/dev/stryker-test/node_modules/@stryker-mutator/core/src/process/InitialTestExecutor.js:41:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
11:12:36 (16352) INFO StrykerCli Trouble figuring out what went wrong? Try `npx stryker run --fileLogLevel trace --logLevel debug` to get some more info.
```

**Stryker config**

```js
module.exports = function(config) {
  config.set({
    mutator: "javascript",
    packageManager: "npm",
    reporters: ["clear-text", "progress"],
    testRunner: "jest",
    transpilers: [],
    coverageAnalysis: "off"
  });
};
```

**Test runner config**

None

**Stryker environment**

```
├─┬ @stryker-mutator/core@2.5.0
│ ├─┬ @stryker-mutator/api@2.5.0
│ ├── @stryker-mutator/util@2.5.0
├─┬ @stryker-mutator/javascript-mutator@2.5.0
│ ├── @stryker-mutator/api@2.5.0 deduped
├─┬ @stryker-mutator/jest-runner@2.5.0
│ ├── @stryker-mutator/api@2.5.0 deduped
```

```
+-- jest@25.1.0
```

**Test runner environment**

```shell
npm test
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 10.16.1
| npm              | 6.14.1
| Operating System | MacOS 10.14.5

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker/files/4282670/stryker.log)

**Comment by simondel** [comment] 2020-03-03 19:31
Hi! This seems to be a duplicate of #1983 

Support for Jest 25 will be released with v3 of Stryker. For now, please downgrade to Jest 24 or wait for v3 of Stryker, sorry!

**Closed by simondel** 2020-03-03 19:31 UTC
Labels: 🐛 Bug

**Comment by simondel** [comment] 2020-03-11 15:48
Hi! Jest 25 support has been released with @stryker-mutator version 3! You can read all about it here: https://stryker-mutator.io/blog/2020-03-11/stryker-version-3

**Comment by statefull** [comment] 2020-09-16 08:47
Still not working with versio > 24. I was using jest version 26 I need to downgrade to version 24 to get it working.  Stricker version 3.3.1.
