### ISSUE TITLE
Can't start 8 parallel browsers on 8 cores CPU

### ISSUE THREAD

**Issue by zxxc** [stryker-mutator/stryker#215] opened 2017-01-05 08:46 UTC
We have about 190 js files with unit test and on windows 10 x64 i7 8 cores 32gb ram
stryker tries to start 8 chromes in parallel and fails with exception that number of opened files is exceeded

i've tried to find a way to increase this limit, but no luck
https://social.technet.microsoft.com/Forums/office/en-US/f2bc07f5-5a2d-40ef-b6f1-7957581bd74c/increasing-the-maximum-open-files-per-session-limit?forum=winserverfiles

for now i fixed it with maxConcurrentTestRunners:5 and CPU load on my PC is about 90-95%
i want to create separate build plan on CI to create reports on weekends and our server much more powerful than my PC

for future maybe it will be acceptable to combine such files into one before start browsers with mutations or smth like that

**Comment by nicojs** [comment] 2017-01-09 12:25
@zxxc thanks for creating this issue.

I think the problem is not that there are 8 child processes starting up, rather Stryker is trying to copy all files into 8 sandboxes at once (without using [graceful-fs](https://github.com/isaacs/node-graceful-fs) or something like that). 

We should make sure that small file system issues do not result in  a crash of Stryker.

**Comment by zxxc** [comment] 2017-01-27 07:47
if it will be useful, i've made screenshot with new graceful-fs

![image](https://cloud.githubusercontent.com/assets/13364984/22363793/e875acdc-e47d-11e6-9513-05f87c21362d.png)

**Comment by nicojs** [comment] 2017-01-27 07:50
@zxxc how did you test it? Because its not released yet. Still hoping that it will work.

**Comment by zxxc** [comment] 2017-01-27 08:13
i've made a clone from git for stryker and stryker-api
npm build for both

and copied all files into node_modules/ in my project directory
then remove limit from stryker.conf.js

and run with first part of my files (11 000 mutations)

What should i do to test your fix correctly?
Log:
[gracefulFstest.txt](https://github.com/stryker-mutator/stryker/files/734673/gracefulFstest.txt)

I tried to find 'graceful' in node_modules/stryker this is result (to be sure that your changes is on a right place):
![image](https://cloud.githubusercontent.com/assets/13364984/22364288/78b872d6-e481-11e6-99b3-a38b57fcf773.png)

**Comment by zxxc** [comment] 2017-01-27 08:19
Is it helps us if we will create one file with all my js code after stryker collect coverage and before stryker will run my 8 browsers?
I have same problem on my teamcity server, but it has only 2 cores on windows 7 and i even can't start 2 browsers (for now i splitted all my files into 4 parts and i run stryker 4 times with maxConcurrentTestRunners:1)
I plan to run stryker on machine with 32 cores in future, but this machine works under Windows, and seems it's better for now to find linux machine with 32 cores

**Comment by nicojs** [comment] 2017-01-27 08:33
I see what the problem is. You forgot to build the typescript files. The best thing you can do is:

* Clone stryker, checkout the master branch
* Do an `npm install`
* Install grunt-cli: `npm i -g grunt-cli`
* Build stryker using `grunt build`
* Go to your project. Uninstall stryker: `npm uninstall stryker`
* Install your local stryker `npm i file:../../stryker-mutator/stryker` (should be the path to stryker using forward slashes)
* Than start stryker like you normally would

If you do the search for `graceful` again, you should see the `*.js` files.

Running on 32 cores would be awesome. Probably you would want to limit the concurrency a bit, maybe put it on 20 or something.

**Comment by zxxc** [comment] 2017-03-31 16:35
![image](https://cloud.githubusercontent.com/assets/13364984/24559892/155128a6-1649-11e7-9cac-d2dd0ffea925.png)
@nicojs hi, i tried new version and it's working now on my machine :)

**Comment by nicojs** [comment] 2017-04-06 08:07
@zxxc very cool stuff!! Can we close this issue?

**Comment by nicojs** [comment] 2017-04-06 08:09
@zxxc on a side note: could you PM me your home address and t-shirt size? So we can send you a t-shirt: https://stryker-mutator.github.io/images/stryker-t-shirt.png

**Comment by zxxc** [comment] 2017-04-06 14:29
yeah, we can close this issue

**Comment by simondel** [comment] 2017-04-07 06:23
Great to hear that you got it working!!

**Closed by simondel** 2017-04-07 06:23 UTC
Labels: bug
