### ISSUE TITLE
HTML report doesn't display right side table for mutators

### ISSUE THREAD

**Issue by MrCappuccino** [stryker-mutator/stryker#1613] opened 2019-07-01 15:06 UTC
### Summary
Here is an image of a proper HTML report with the table on the right hand side of the page:
![image](https://user-images.githubusercontent.com/10047484/60446151-0b5cdd80-9c21-11e9-83d8-576b6f598b1a.png)

However I am only getting this:
![image](https://user-images.githubusercontent.com/10047484/60446277-5a0a7780-9c21-11e9-9b23-f4aa12997a51.png)

As you can see the table on the right side does not appear. Perhaps it's because I'm only using jest? (This is a create-react-app)

### Stryker config

```js
module.exports = function(config) {
  config.set({
    packageManager: 'npm',
    mutate: [
      'src/**/*.js?(x)',
      '!src/**/*@(.test|.spec|Spec).js?(x)',
      '!src/serviceWorker.js',
      '!src/App.js',
      '!src/index.js',
    ],
    mutator: 'javascript',
    testRunner: 'jest',
    reporters: ['progress', 'html', 'clear-text'],
    coverageAnalysis: 'off',
    jest: {
      projectType: 'react',
    },
  });
};

```

### Stryker environment

```
├─┬ @stryker-mutator/core@2.0.0
│ ├─┬ @stryker-mutator/api@2.0.0
│ ├── @stryker-mutator/util@2.0.0
├─┬ @stryker-mutator/html-reporter@2.0.0
│ ├── @stryker-mutator/api@2.0.0 deduped
│ ├── @stryker-mutator/util@2.0.0 deduped
├─┬ @stryker-mutator/javascript-mutator@2.0.0
│ ├── @stryker-mutator/api@2.0.0 deduped
├─┬ @stryker-mutator/jest-runner@2.0.0
│ ├── @stryker-mutator/api@2.0.0 deduped
```

### Test runner environment

```
npm test

```

```json
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | v10.16.0
| npm              | 6.9.2
| Operating System | 5.1.15-arch1-1-ARCH

### Add stryker.log

[stryker.log](https://github.com/stryker-mutator/stryker/files/3346215/stryker.log)

**Comment by kmdrGroch** [comment] 2019-07-02 08:27
'expand all' button doesn't open it? And these reports look completely different. I think docs are outdated or we can get 2 different HTML files [I mean styles, like buttons. Maybe lack of right part is caused by that too(?)]

**Comment by MrCappuccino** [comment] 2019-07-02 09:09
> 'expand all' button doesn't open it? And these reports look completely different. I think docs are outdated or we can get 2 different HTML files [I mean styles, like buttons. Maybe lack of right part is caused by that too(?)]

No, the expand all button does not open the right side table.

**Comment by nicojs** [comment] 2019-07-04 06:11
@MrCappuccino we actually removed the right-side table (and didn't update the example screenshot) when we moved the functionality to the https://github.com/stryker-mutator/mutation-testing-elements web component library .

We thought it was more of clutter, as it didn't present any additional information. Do you really miss it? If so, what information are you missing exactly? Any feedback is welcome at the mutation-testing-elements repo: https://github.com/stryker-mutator/mutation-testing-elements/issues.

**Comment by MrCappuccino** [comment] 2019-07-04 08:32
> @MrCappuccino we actually removed the right-side table (and didn't update the example screenshot) when we moved the functionality to the https://github.com/stryker-mutator/mutation-testing-elements web component library .
> 
> We thought it was more of clutter, as it didn't present any additional information. Do you really miss it? If so, what information are you missing exactly? Any feedback is welcome at the mutation-testing-elements repo: https://github.com/stryker-mutator/mutation-testing-elements/issues.

What I found useful is that it explicitly tells you what mutation happened and what was replaced in the code.

**Comment by nicojs** [comment] 2019-07-04 19:45
Cool, feel free to open an issue at mutation-testing-elements. I'm closing this one since the problem is not with Stryker itself.

Note: by fixing this issue in mutation-testing-elements, other mutation testing frameworks using the same report will also benefit from any improvements we make.

**Closed by nicojs** 2019-07-04 19:45 UTC
