### ISSUE TITLE
Karma config not being picked up for the sandbox environment

### ISSUE THREAD

**Issue by JordyLangen** [stryker-mutator/stryker#1171] opened 2018-10-03 21:30 UTC
### Summary

I've set up an existing project with stryker, and I'm finding difficulties getting it to work. I have one issue in particular. The setup of the project is like this: we have an angular based project which we build with webpack (not the anguar-cli, please don't get me started) and we use karma & jasmine for testing.

When executing `stryker run` I get the follow error message:

> Unable to find karma config at "karma.conf.js" (tried to load from C:\\[hidden]\\.stryker-tmp\sandbox4821780\karma.conf.js). Please check your stryker config. You might need to make sure the file is included in the sandbox directory.

I checked the documentation for it the at https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/README.md#files-in-the-sandbox and ran the command is said to provide the default setup, providing me with th following output:

```
$ git ls-files --others --exclude-standard --cached --exclude .stryker-tmp | grep karma
karma.conf.js
```

So I'm not sure why the karma file is not included in the temp/sandbox directory

### Stryker config

```js
module.exports = function(config) {
  config.set({
    mutator: "typescript",
    packageManager: "npm",
    reporters: ["html", "clear-text", "progress", "dashboard"],
    testRunner: "karma",
    transpilers: ["typescript", "webpack"],
    testFramework: "jasmine",
    coverageAnalysis: "off",
    karma: {
      projectType: "custom",
      configFile: "karma.conf.js",
      config: {}
    },
    tsconfigFile: "tsconfig.json",
    mutate: ["src/**/*.ts"],
    webpack: {
      configFile: "webpack.config.dev.js"
    }
  });
};
```

### Stryker environment

```
+-- stryker@0.29.5
+-- stryker-api@0.21.2
+-- stryker-html-reporter@0.16.4
+-- stryker-jasmine@0.10.3
+-- stryker-karma-runner@0.18.3
+-- stryker-typescript@0.14.2
+-- stryker-webpack-transpiler@0.7.5
```

```
+-- karma@2.0.2
+-- karma-jasmine@1.1.0
+-- jasmine-core@2.8.0
+-- jasmine-spec-reporter@4.2.1
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | v8.1.2
| npm              | 5.0.3
| Operating System |  Windows

**Comment by simondel** [comment] 2018-10-04 04:58
Thanks for opening this issue! What do you see inside of the sandbox folder? Is the file actually there?

**Comment by JordyLangen** [comment] 2018-10-04 06:05
No the file really isn't copied over to the sandbox directory, even double checked that :sweat_smile:

**Comment by JordyLangen** [comment] 2018-10-06 13:41
[stryker.log](https://github.com/stryker-mutator/stryker/files/2453068/stryker.log)

**Comment by nicojs** [comment] 2018-10-09 06:41
@JordyLangen I think i know what the problem is. I can see that your karma.conf.js file is transpiled by typescript. After transpiling, it no longer resides in the root of your project, instead it is located in tsc-output:
`'C:\\projects\\******-******-app\\dist\\out-tsc\\karma.conf.js'`.

What does your tsconfig.json file look like?

**Comment by simondel** [comment] 2019-09-25 13:25
Since didn't hear anything back, I'm closing this issue for now.

**Closed by simondel** 2019-09-25 13:25 UTC
