### ISSUE TITLE
Can't run stryker with es6 code

### ISSUE THREAD

**Issue by aviram26** [stryker-mutator/stryker#916] opened 2018-06-28 10:48 UTC
### Summary
Following your [main page](http://stryker-mutator.io/quickstart.html) instructions and running with es6 + mocha I get `SyntaxError: Unexpected token import`

Also read https://github.com/stryker-mutator/stryker-jest-runner/issues/40, but didn't see a solution.

I have a poc repo here: https://github.com/aviram26/stryker-poc

To reproduce run:
* `npm install`
* `npm run mutation`

### Stryker config

```js
module.exports = function (config) {
    config.set({
        testRunner: 'mocha',
        testFramework: 'mocha',

        mutator: 'javascript',
        mutate: [
            'src/js/**/*.js',
        ],
        files: [
            'src/**/*.js',
            'test/**/*.js',
        ],

        transpilers: ['webpack'],
        reporter: ['clear-text', 'progress'],
        coverageAnalysis: 'off',
        webpack: {
            configFile: 'webpack.config.js'
        },
        logLevel: 'trace',
    });
};
```

### Stryker environment

```
+-- stryker@0.24.1
+-- stryker-api@0.17.2
+-- stryker-javascript-mutator@0.7.2
+-- stryker-mocha-framework@0.10.2
+-- stryker-mocha-runner@0.12.2
+-- stryker-webpack-transpiler@0.5.1
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             |  8.11.2
| npm              |  6.1.0
| Operating System |  windows 7

Thanks!

**Comment by simondel** [comment] 2018-06-28 10:49
Thansk for opening this issue and creating a reproduction repo! I'll give it a try.

**Comment by simondel** [comment] 2018-06-28 11:02
Could you please update the repo with a way to run the unit tests?

**Comment by aviram26** [comment] 2018-06-28 11:20
Added.

Update with `npm install`

And run `npm run test`

**Comment by Archcry** [comment] 2018-06-28 16:58
I've taken a quick look and the problem lies in the fact that the tests are not compatible with node when they're not transpiled and bundled with Webpack. It complains about not being able to use `import` which makes perfect sense because node does not have `import`. We've refactored and changed the Webpack transpiler for Stryker a lot lately and I would not know how to get this situation working from the top of my head. Maybe @nicojs could shed some light on the matter?

**Comment by aviram26** [comment] 2018-07-04 06:18
Guys, maybe you have an example running `stryker` with `typescript` and `webpack`?

It's basically the same process of transpiling with webpack and running the specified mutator plugin with the specified test runner/framework, right?

**Comment by nicojs** [comment] 2018-07-06 06:44
@aviram26 that's an interesting setup. I've created a PR that makes stryker work. I'm closing this issue for now, if you have any questions or problems, please let us know.

https://github.com/aviram26/stryker-poc/pull/1

With this pull request I made Stryker work with your setup.

Your test pipeline looks like this:

```
        _________                _______
es6 => | webpack | ==> es5  ==> | mocha | ==> test output
        _________                _______
```

This was masked by the fact you were using mocha-webpack. The first thing I did was remove that in favor of building the pipeline yourself.

After that, it was pretty straightforward to configure this pipeline in Stryker using the webpack plugin.

**Closed by nicojs** 2018-07-06 06:44 UTC

**Comment by aviram26** [comment] 2018-07-16 09:50
@nicojs -Thanks!!
I will update if there is anything interesting...

**Comment by johnd1994** [comment] 2019-05-30 14:18
Hello. I  think i have a similar issue and i didnt want to bother you with another issue. I am also very new to this.

I have a test written in ES6, which imports other modules written as well in ES6.
I am trying to run stryker on it.

I dont understand how you guys @nicojs and @aviram26 succeed in it.

My **package.json** is : 
```
"devDependencies": {
                "@babel/core": "^7.4.5",
                "@babel/preset-env": "^7.4.5",
                "@stryker-mutator/core": "^2.0.0",
                "@stryker-mutator/javascript-mutator": "^2.0.0",
                "@stryker-mutator/mocha-framework": "^2.0.0",
                "@stryker-mutator/mocha-runner": "^2.0.0",
                "@stryker-mutator/webpack-transpiler": "^2.0.0",
                "babel-loader": "^8.0.6",
                "esm": "3",
                "gulp": "4",
                "mocha": "5",
                "webpack": "^4.32.2",
                "webpack-cli": "^3.3.2"
        },
        "scripts": {
                "test": "mocha -r esm --ui tdd ./test/index.js",
                "build": "webpack"
        }
```

my **stryker.conf.js** is : 
```
module.exports = function(config) {
  config.set({
    files : ["./lib/index.js", "./lib/constants.js", "./test/index.js"],
    mutator: "javascript",
    packageManager: "npm",
    reporters: ["clear-text", "progress"],
    testRunner: "mocha",
    webpack : {
      configFile: 'webpack.config.js',
      silent:true
    },
    transpilers: ["webpack"],
    testFramework: "mocha",
    coverageAnalysis: "off"
  });
};
```
my **webpack.config.js** is : 
```
module.exports = {
  entry: './test/index.js',
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      }
    ]
  }
};
```

i run it with 
```
npx stryker run --fileLogLevel trace --logLevel debug
```

but i am getting : 
```
ERROR InitialTestExecutor One or more tests resulted in an error:
        SyntaxError: Unexpected identifier
/sandboxedModuleHeros/code/.stryker-tmp/sandbox4665959/test/index.js:1
(function (exports, require, module, __filename, __dirname) { import assert from 'assert';
                                                                     ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Proxy.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```
