### ISSUE TITLE
Potential bug with concurrency

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#2327] opened 2020-07-21 01:10 UTC
Right now `maxConcurrentTestRunners` is deprecated and will be removed soon.
In optionsValidator we can see some checks being done for `maxConcurrentTestRunners` and assigning it to `concurrency`.

But
There is no check for `concurrency`. What values user can input? Any number? Shouldn't we make similar checks for it as well as it is for `maxConcurrentTestRunners` now?

**Comment by nicojs** [comment] 2020-07-28 05:54
Thanks for taking a look at the beta code! Appreciated.

Do you mean, no check on the max value of `--concurrency`? This is "by design" on my end. The reasoning behind it is that I don't want to limit users anymore. You might have a project that uses a lot of `sleep` or io operations. The default (n-1) should be fine for most projects.

The `ConcurrencyTokenProvider` will take care of deciding how many workers will be started for checkers and test runners.

https://github.com/stryker-mutator/stryker/blob/69358e1423701c730e29d303119a08d74081f340/packages/core/src/concurrent/concurrency-token-provider.ts#L22-L33

**Comment by nicojs** [comment] 2020-08-14 11:31
Closing this issue for now. If you feel like this still needs to be addressed, let me know.

**Closed by nicojs** 2020-08-14 11:31 UTC
Labels: 🐛 Bug
